// ADR index generator + SDD §15 status sync (feedback IMP-4). Front-matter is
// the single source of truth for ADR status/title.
const fs = require('node:fs');
const path = require('node:path');
const { readFrontMatter } = require('./consistency-gate.js');

const I_START = '<!-- ADR-INDEX:START — generated by adr-index.js, do not edit between markers -->';
const I_END = '<!-- ADR-INDEX:END -->';
const S_START = '<!-- ADR-STATUS:START — generated by adr-index.js, do not edit between markers -->';
const S_END = '<!-- ADR-STATUS:END -->';

function loadAdrFm(dir) {
  const adrDir = path.join(dir, 'adr');
  const out = [];
  if (!fs.existsSync(adrDir)) return out;
  for (const f of fs.readdirSync(adrDir).sort()) {
    if (!f.endsWith('.md') || f === 'index.md') continue;
    const fm = readFrontMatter(fs.readFileSync(path.join(adrDir, f), 'utf8'));
    if (fm.id) out.push(fm);
  }
  return out;
}

function renderIndex(adrs) {
  const rows = adrs.map(a =>
    `| ${a.id} | ${a.title || '—'} | ${a.status || '—'} | ${a.date || '—'} |`).join('\n');
  return `${I_START}\n\n# ADR Index\n\n| ADR | Title | Status | Date |\n| --- | --- | --- | --- |\n${rows}\n\n${I_END}\n`;
}

function writeIndex(dir) {
  const adrs = loadAdrFm(dir);
  fs.writeFileSync(path.join(dir, 'adr', 'index.md'), renderIndex(adrs));
  return adrs;
}

function syncSddStatus(sddText, adrs) {
  const s = String(sddText || '');
  const si = s.indexOf(S_START), ei = s.indexOf(S_END);
  if (si === -1 || ei === -1 || ei < si) return s;
  const status = Object.fromEntries(adrs.map(a => [a.id, a.status || '—']));
  const region = s.slice(si + S_START.length, ei);
  let statusCol = -1;
  const rewritten = region.split('\n').map(line => {
    if (!/^\s*\|/.test(line)) return line;
    const cells = line.split('|');                       // ['', ' c0 ', ' c1 ', ..., '']
    const trimmed = cells.map(c => c.trim());
    if (statusCol === -1 && trimmed.some(c => c.toLowerCase() === 'status')) {
      statusCol = trimmed.findIndex(c => c.toLowerCase() === 'status');
      return line; // header row
    }
    if (trimmed.every(c => /^:?-+:?$/.test(c) || c === '')) return line; // separator
    if (statusCol === -1) return line;
    const idMatch = (trimmed[1] || '').replace(/[<>]/g, '').match(/ADR-\d+/);
    if (!idMatch || !(idMatch[0] in status)) return line;
    cells[statusCol] = ` ${status[idMatch[0]]} `;
    return cells.join('|');
  }).join('\n');
  return s.slice(0, si + S_START.length) + rewritten + s.slice(ei);
}

module.exports = { loadAdrFm, renderIndex, writeIndex, syncSddStatus, I_START, I_END, S_START, S_END };

if (require.main === module) {
  const dir = path.resolve(process.argv[2] || '.product');
  const adrs = writeIndex(dir);
  const sddPath = path.join(dir, 'sdd', 'sdd.md');
  if (fs.existsSync(sddPath)) {
    fs.writeFileSync(sddPath, syncSddStatus(fs.readFileSync(sddPath, 'utf8'), adrs));
  }
  console.log(`adr-index: wrote ${adrs.length} ADR(s); synced SDD §15 status where present.`);
}
