const fs = require('node:fs');
const path = require('node:path');

const C = require('./id-conventions.js');
const { lintText } = require('./lint-ids.js');
const PREFIX = C.PREFIX;
const MEMBER = C.MEMBER;
// A reference group: an anchor member plus a run of continuation operators + members.
const GROUP_RE = new RegExp(
  MEMBER + '(?:\\s*(?:…|\\.\\.\\.|\\.\\.|[/,])\\s*(?:' + PREFIX + '-)?' + C.CAT + '\\d+[a-z]?|/[a-z](?![a-z\\d]))*', 'g');
// Tokens inside a group. Member alternative first so 'FR-001' wins over '..'+digits.
const TOKEN_RE = new RegExp(
  MEMBER + '|…|\\.\\.\\.|\\.\\.|[/,]|' + C.CAT + '\\d+[a-z]?|[a-z]', 'g');
const RANGE_OPS = new Set(['…', '...', '..']);
const LIST_OPS = new Set(['/', ',']);
const MAX_SPAN = 200;

const START = '<!-- COVERAGE-INDEX:START — generated by traceability.js, do not edit between markers -->';
const END = '<!-- COVERAGE-INDEX:END -->';
const REQ_RE = C.REQ_RE;

function pad(n, width) {
  const s = String(n);
  return s.length >= width ? s : '0'.repeat(width - s.length) + s;
}

function memberParts(tok) {
  const m = C.parseMember(tok);
  if (m) return { prefix: m.prefix, cat: m.cat, num: m.num, suf: m.suf };
  const bare = tok.match(/^([A-Z]{0,2})(\d+)([a-z]?)$/);
  if (bare) return { prefix: null, cat: bare[1] || '', num: bare[2], suf: bare[3] };
  const bareSuf = tok.match(/^([a-z])$/);
  if (bareSuf) return { prefix: null, cat: '', num: null, suf: bareSuf[1] };
  return null;
}

function expandRange(startId, endId) {
  const fa = C.familyOf(startId), fb = C.familyOf(endId);
  const a = C.parseMember(startId), b = C.parseMember(endId);
  if (!a || !b || fa !== fb) return [startId, endId];
  const start = parseInt(a.num, 10), end = parseInt(b.num, 10);
  const width = Math.max(a.num.length, b.num.length);
  if (end < start || (end - start) >= MAX_SPAN) {
    if ((end - start) >= MAX_SPAN) {
      console.warn(`traceability: range ${startId}..${endId} exceeds ${MAX_SPAN}; emitting endpoints only`);
    }
    return [startId, endId];
  }
  const out = [];
  for (let i = start; i <= end; i++) out.push(`${fa}${pad(i, width)}`);
  return out;
}

function parseGroup(group) {
  const toks = group.match(TOKEN_RE) || [];
  const ids = [];
  let prefix = null, cat = '', prev = null, pendingRange = false;
  for (const tok of toks) {
    if (RANGE_OPS.has(tok)) { pendingRange = true; continue; }
    if (LIST_OPS.has(tok)) { pendingRange = false; continue; }
    const parts = memberParts(tok);
    if (!parts) continue;
    if (parts.prefix) prefix = parts.prefix;
    if (!prefix) continue;
    cat = parts.prefix ? parts.cat : (parts.cat || cat); // inherit category for bare tails
    const num = parts.num !== null ? parts.num : (prev && prev.num);
    if (!num) continue;
    const cur = { prefix, cat, num, suf: parts.suf };
    const curId = `${cur.prefix}-${cur.cat}${cur.num}${cur.suf}`;
    if (pendingRange && prev) {
      ids.pop(); // remove prev's standalone push; replace with the full range
      for (const r of expandRange(`${prev.prefix}-${prev.cat}${prev.num}${prev.suf}`, curId)) ids.push(r);
    } else {
      ids.push(curId);
    }
    prev = cur;
    pendingRange = false;
  }
  return ids;
}

function refTuple(id) {
  const m = C.parseMember(id);
  return m ? [m.prefix, m.cat, parseInt(m.num, 10), m.suf] : [id, '', 0, ''];
}
function refCompare(a, b) {
  const x = refTuple(a), y = refTuple(b);
  if (x[0] !== y[0]) return x[0] < y[0] ? -1 : 1;
  if (x[1] !== y[1]) return x[1] < y[1] ? -1 : 1;
  if (x[2] !== y[2]) return x[2] - y[2];
  return x[3] < y[3] ? -1 : x[3] > y[3] ? 1 : 0;
}

function parseRefs(text) {
  const groups = String(text || '').match(GROUP_RE) || [];
  const all = [];
  for (const g of groups) all.push(...parseGroup(g));
  return [...new Set(all)].sort(refCompare);
}

function slugify(heading) {
  return heading.trim().toLowerCase().replace(/[^\w\s-]/g, '').replace(/\s+/g, '-');
}

function sectionAnchors(markdown, id) {
  const lines = String(markdown || '').split(/\r?\n/);
  const out = [];
  let cur = null, buf = [];
  const flush = () => {
    if (cur && parseRefs(buf.join('\n')).includes(id) && !out.some(o => o.slug === cur.slug)) {
      out.push(cur);
    }
  };
  for (const line of lines) {
    const m = line.match(/^(#{2,3})\s+(.*\S)\s*$/);
    if (m) { flush(); cur = { section: m[2].trim(), slug: slugify(m[2]) }; buf = []; }
    else buf.push(line);
  }
  flush();
  return out;
}

function linksWithin(text, leftRe, rightRe) {
  const map = new Map();
  // Scope co-reference to a single sentence or line, not the whole paragraph,
  // so "AR-001 implements FR-001. AR-002 implements FR-002." does not cross-link.
  for (const seg of String(text || '').split(/\n+|(?<=\.)\s+/)) {
    const ids = parseRefs(seg);
    const lefts = ids.filter(id => leftRe.test(id));
    const rights = ids.filter(id => rightRe.test(id));
    for (const l of lefts) {
      const s = map.get(l) || new Set();
      rights.forEach(r => { if (r !== l) s.add(r); });
      map.set(l, s);
    }
  }
  const out = new Map();
  for (const [k, s] of map) out.set(k, [...s].sort(refCompare));
  return out;
}

// Structurally read an "Architectural Requirements" table: AR id from the ID
// column, requirement ids from the Source column. Independent of sentence
// boundaries, unlike linksWithin (feedback A2).
function parseArTable(markdown) {
  const lines = String(markdown || '').split(/\r?\n/);
  const map = new Map();
  let cols = null; // {id, source} column indices
  for (const line of lines) {
    if (!/^\s*\|/.test(line)) { cols = null; continue; }
    const cells = line.split('|').slice(1, -1).map(c => c.trim());
    if (cells.every(c => /^:?-+:?$/.test(c) || c === '')) continue; // separator row
    const lower = cells.map(c => c.toLowerCase());
    if (lower.includes('id') && lower.includes('source')) {
      cols = { id: lower.indexOf('id'), source: lower.indexOf('source') };
      continue;
    }
    if (!cols) continue;
    const arId = (cells[cols.id] || '').match(/^AR-[A-Z]{0,2}\d+[a-z]?/);
    if (!arId) continue;
    const reqs = parseRefs(cells[cols.source] || '').filter(id => REQ_RE.test(id));
    if (reqs.length) map.set(arId[0], reqs);
  }
  return map;
}

function buildMatrix({ prd = '', sdd = '', adrs = {}, srs = '', sad = '' } = {}) {
  // SRS mode: when an SRS is present it is the canonical source of FR/NFR;
  // BR always comes from the PRD. With no SRS, FR/BR/NFR all come from the PRD.
  const hasSrs = String(srs).trim() !== '';
  const fnrRefs = parseRefs(hasSrs ? srs : prd).filter(id => /^(FR|NFR)-/.test(id));
  const brRefs = parseRefs(prd).filter(id => /^BR-/.test(id));
  const prdRefs = [...new Set([...fnrRefs, ...brRefs, ...parseRefs(prd).filter(id => /^UAT-/.test(id))])].sort(refCompare);
  const sddSet = new Set(parseRefs(sdd));
  const adrSets = Object.entries(adrs).map(([k, txt]) => {
    const m = k.match(/ADR-\d+/);
    return [m ? m[0] : k, new Set(parseRefs(txt))];
  });
  const adrsFor = id => adrSets.filter(([, s]) => s.has(id)).map(([k]) => k).sort(refCompare);

  // SAD mode: when a SAD is present it is the canonical source of AR-NNN; otherwise AR lives in the SDD.
  const arSource = String(sad).trim() !== '' ? sad : sdd;

  const uatVerifies = linksWithin(prd, /^UAT-/, REQ_RE);
  const arTrace = linksWithin(arSource, /^AR-/, REQ_RE);

  const arTable = parseArTable(arSource);
  for (const [ar, reqs] of arTable) {
    const merged = new Set([...(arTrace.get(ar) || []), ...reqs]);
    arTrace.set(ar, [...merged].sort(refCompare));
  }

  const uatsForReq = new Map();
  for (const [uat, reqs] of uatVerifies) {
    for (const r of reqs) {
      const set = uatsForReq.get(r) || new Set();
      set.add(uat);
      uatsForReq.set(r, set);
    }
  }

  const requirements = prdRefs.filter(id => REQ_RE.test(id)).map(id => ({
    id,
    family: id.split('-')[0],
    inSdd: sddSet.has(id),
    sections: sectionAnchors(sdd, id),
    adrs: adrsFor(id),
    uats: [...(uatsForReq.get(id) || [])].sort(refCompare),
    coverage: sddSet.has(id) ? 'covered' : 'orphan',
  }));

  const uats = prdRefs.filter(id => /^UAT-/.test(id)).map(id => ({
    id, verifies: uatVerifies.get(id) || [],
  }));

  const ars = parseRefs(arSource).filter(id => /^AR-/.test(id)).map(id => ({
    id, tracesTo: arTrace.get(id) || [], adrs: adrsFor(id),
  }));

  const cSource = [prd, srs, sad, sdd].join('\n');
  const cTrace = linksWithin(cSource, /^C-/, REQ_RE);
  const constraints = parseRefs(cSource).filter(id => /^C-/.test(id)).map(id => ({
    id, tracesTo: cTrace.get(id) || [], adrs: adrsFor(id),
  }));

  const orphans = requirements.filter(r => r.coverage === 'orphan').map(r => r.id);
  const unclassified = [...new Set([prd, sdd, srs, sad, ...Object.values(adrs)]
    .flatMap(txt => lintText(txt).malformed))].sort();
  return { requirements, ars, uats, orphans, unclassified, constraints };
}

function fmtSections(secs) {
  return secs.length ? secs.map(s => `[${s.section}](#${s.slug})`).join(', ') : '—';
}

function renderCoverageBlock(matrix) {
  const { requirements, ars, uats, orphans } = matrix;
  let out = `> ${orphans.length} orphan(s): genuine coverage gaps — a requirement defined in the PRD with no matching mention in the SDD. Notation-only artifacts are already resolved by symmetric ID expansion.\n\n`;
  if (orphans.length) out += `**Orphans:** ${orphans.join(', ')}\n\n`;
  out += '| Requirement | In SDD | SDD Sections | Related ADRs | UAT | Coverage |\n';
  out += '| --- | --- | --- | --- | --- | --- |\n';
  out += requirements.map(r =>
    `| ${r.id} | ${r.inSdd ? 'yes' : 'no'} | ${fmtSections(r.sections)} | ${r.adrs.join(', ') || '—'} | ${r.uats.join(', ') || '—'} | ${r.coverage === 'covered' ? '✅ Covered' : '⚠️ Orphan'} |`
  ).join('\n') + '\n';
  if (ars.length) {
    out += '\n**Architectural Requirements**\n\n| AR | Traces to | In ADRs |\n| --- | --- | --- |\n';
    out += ars.map(a => `| ${a.id} | ${a.tracesTo.join(', ') || '—'} | ${a.adrs.join(', ') || '—'} |`).join('\n') + '\n';
  }
  if (matrix.constraints && matrix.constraints.length) {
    out += '\n**Constraints**\n\n| Constraint | Traces to | In ADRs |\n| --- | --- | --- |\n';
    out += matrix.constraints.map(c => `| ${c.id} | ${c.tracesTo.join(', ') || '—'} | ${c.adrs.join(', ') || '—'} |`).join('\n') + '\n';
  }
  if (uats.length) {
    out += '\n**Acceptance Tests**\n\n| UAT | Verifies |\n| --- | --- |\n';
    out += uats.map(u => `| ${u.id} | ${u.verifies.join(', ') || '—'} |`).join('\n') + '\n';
  }
  if (matrix.unclassified && matrix.unclassified.length) {
    out += `\n> ⚠️ ${matrix.unclassified.length} unclassified ID-shaped token(s) (check ID format): ${matrix.unclassified.join(', ')}\n`;
  }
  return out;
}

function renderMarkdown(matrix) {
  return `# Traceability Matrix\n\n${renderCoverageBlock(matrix)}`;
}

function esc(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function renderHtml(matrix) {
  const trs = matrix.requirements.map(r =>
    `<tr><td>${esc(r.id)}</td><td class="${r.inSdd ? 'ok' : 'gap'}">${r.inSdd ? 'yes' : 'no'}</td><td>${esc(r.adrs.join(', ') || '—')}</td><td>${esc(r.uats.join(', ') || '—')}</td><td>${r.coverage === 'covered' ? '✅' : '⚠️'}</td></tr>`
  ).join('');
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Traceability Matrix</title>
<style>body{font-family:system-ui,sans-serif;margin:2rem}table{border-collapse:collapse}td,th{border:1px solid #ccc;padding:.4rem .6rem}.gap{color:#b00;font-weight:bold}.ok{color:#070}</style>
</head><body><h1>Traceability Matrix</h1>
<table><thead><tr><th>Requirement</th><th>In SDD</th><th>Related ADRs</th><th>UAT</th><th>Coverage</th></tr></thead>
<tbody>${trs}</tbody></table></body></html>`;
}

function injectCoverage(sdd, block) {
  const wrapped = `${START}\n\n${block}\n${END}`;
  const s = String(sdd || '');
  const si = s.indexOf(START), ei = s.indexOf(END);
  if (si !== -1 && ei !== -1 && ei > si) {
    return s.slice(0, si) + wrapped + s.slice(ei + END.length);
  }
  const sep = s.endsWith('\n') ? '' : '\n';
  return s + `${sep}\n## 16. Requirement Coverage Index\n\n${wrapped}\n`;
}

function loadProduct(dir) {
  const read = p => fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : '';
  const adrDir = path.join(dir, 'adr');
  const adrs = {};
  if (fs.existsSync(adrDir)) {
    for (const f of fs.readdirSync(adrDir)) {
      if (f.endsWith('.md')) {
        const m = f.match(/ADR-\d+/);
        adrs[m ? m[0] : f] = read(path.join(adrDir, f));
      }
    }
  }
  return {
    prd: read(path.join(dir, 'prd', 'prd.md')),
    sdd: read(path.join(dir, 'sdd', 'sdd.md')),
    srs: read(path.join(dir, 'srs', 'srs.md')),
    sad: read(path.join(dir, 'sad', 'sad.md')),
    adrs,
  };
}

module.exports = {
  parseRefs, expandRange, sectionAnchors, parseArTable, buildMatrix,
  renderMarkdown, renderHtml, renderCoverageBlock, injectCoverage, loadProduct,
};

if (require.main === module) {
  const dir = process.argv[2] || '.product';
  const matrix = buildMatrix(loadProduct(dir));
  if (matrix.unclassified.length) {
    console.warn(`traceability: saw ${matrix.unclassified.length} token(s) it could not classify: ${matrix.unclassified.join(', ')}`);
  }
  fs.writeFileSync(path.join(dir, 'traceability.md'), renderMarkdown(matrix));
  fs.writeFileSync(path.join(dir, 'traceability.html'), renderHtml(matrix));
  const sddPath = path.join(dir, 'sdd', 'sdd.md');
  if (fs.existsSync(sddPath)) {
    fs.writeFileSync(sddPath, injectCoverage(fs.readFileSync(sddPath, 'utf8'), renderCoverageBlock(matrix)));
  } else {
    console.warn(`traceability: ${sddPath} not found; skipped coverage-index injection.`);
  }
  console.log(`Wrote traceability for ${matrix.requirements.length} requirements (${matrix.orphans.length} orphan(s)).`);
}
