const fs = require('node:fs');
const path = require('node:path');

const PREFIX = '(?:FR|BR|NFR|AR|UAT|ADR)';
const MEMBER = PREFIX + '-\\d+[a-z]?';
// A reference group: an anchor member plus a run of continuation operators + members.
const GROUP_RE = new RegExp(
  MEMBER + '(?:\\s*(?:…|\\.\\.\\.|\\.\\.|[/,])\\s*(?:' + PREFIX + '-)?\\d+[a-z]?|/[a-z](?![a-z\\d]))*', 'g');
// Tokens inside a group. Member alternative first so 'FR-001' wins over '..'+digits.
const TOKEN_RE = new RegExp(
  PREFIX + '-\\d+[a-z]?|…|\\.\\.\\.|\\.\\.|[/,]|\\d+[a-z]?|[a-z]', 'g');
const RANGE_OPS = new Set(['…', '...', '..']);
const LIST_OPS = new Set(['/', ',']);
const MAX_SPAN = 200;

const START = '<!-- COVERAGE-INDEX:START — generated by traceability.js, do not edit between markers -->';
const END = '<!-- COVERAGE-INDEX:END -->';
const REQ_RE = /^(FR|BR|NFR)-/;

function pad(n, width) {
  const s = String(n);
  return s.length >= width ? s : '0'.repeat(width - s.length) + s;
}

function memberParts(tok) {
  const withPrefix = tok.match(/^(FR|BR|NFR|AR|UAT|ADR)-(\d+)([a-z]?)$/);
  if (withPrefix) return { prefix: withPrefix[1], num: withPrefix[2], suf: withPrefix[3] };
  const bare = tok.match(/^(\d+)([a-z]?)$/);
  if (bare) return { prefix: null, num: bare[1], suf: bare[2] };
  const bareSuf = tok.match(/^([a-z])$/);
  if (bareSuf) return { prefix: null, num: null, suf: bareSuf[1] };
  return null;
}

function expandRange(startId, endId) {
  const a = startId.match(/^([A-Z]+)-(\d+)([a-z]?)$/);
  const b = endId.match(/^([A-Z]+)-(\d+)([a-z]?)$/);
  if (!a || !b || a[1] !== b[1]) return [startId, endId];
  const start = parseInt(a[2], 10), end = parseInt(b[2], 10);
  const width = Math.max(a[2].length, b[2].length);
  if (end < start || (end - start) >= MAX_SPAN) {
    if ((end - start) >= MAX_SPAN) {
      console.warn(`traceability: range ${startId}..${endId} exceeds ${MAX_SPAN}; emitting endpoints only`);
    }
    return [startId, endId];
  }
  const out = [];
  for (let i = start; i <= end; i++) out.push(`${a[1]}-${pad(i, width)}`);
  return out;
}

function parseGroup(group) {
  const toks = group.match(TOKEN_RE) || [];
  const ids = [];
  let prefix = null, prev = null, pendingRange = false;
  for (const tok of toks) {
    if (RANGE_OPS.has(tok)) { pendingRange = true; continue; }
    if (LIST_OPS.has(tok)) { pendingRange = false; continue; }
    const parts = memberParts(tok);
    if (!parts) continue;
    if (parts.prefix) prefix = parts.prefix;
    if (!prefix) continue;
    const num = parts.num !== null ? parts.num : (prev && prev.num);
    if (!num) continue;
    const cur = { prefix, num, suf: parts.suf };
    if (pendingRange && prev) {
      ids.pop(); // remove prev's standalone push; replace with the full range
      for (const r of expandRange(`${prev.prefix}-${prev.num}${prev.suf}`, `${cur.prefix}-${cur.num}${cur.suf}`)) {
        ids.push(r);
      }
    } else {
      ids.push(`${cur.prefix}-${cur.num}${cur.suf}`);
    }
    prev = cur;
    pendingRange = false;
  }
  return ids;
}

function refTuple(id) {
  const m = id.match(/^([A-Z]+)-(\d+)([a-z]?)$/);
  return m ? [m[1], parseInt(m[2], 10), m[3]] : [id, 0, ''];
}
function refCompare(a, b) {
  const x = refTuple(a), y = refTuple(b);
  if (x[0] !== y[0]) return x[0] < y[0] ? -1 : 1;
  if (x[1] !== y[1]) return x[1] - y[1];
  return x[2] < y[2] ? -1 : x[2] > y[2] ? 1 : 0;
}

function parseRefs(text) {
  const groups = String(text || '').match(GROUP_RE) || [];
  const all = [];
  for (const g of groups) all.push(...parseGroup(g));
  return [...new Set(all)].sort(refCompare);
}

function slugify(heading) {
  return heading.trim().toLowerCase().replace(/[^\w\s-]/g, '').replace(/\s+/g, '-');
}

function sectionAnchors(markdown, id) {
  const lines = String(markdown || '').split(/\r?\n/);
  const out = [];
  let cur = null, buf = [];
  const flush = () => {
    if (cur && parseRefs(buf.join('\n')).includes(id) && !out.some(o => o.slug === cur.slug)) {
      out.push(cur);
    }
  };
  for (const line of lines) {
    const m = line.match(/^(#{2,3})\s+(.*\S)\s*$/);
    if (m) { flush(); cur = { section: m[2].trim(), slug: slugify(m[2]) }; buf = []; }
    else buf.push(line);
  }
  flush();
  return out;
}

function linksWithin(text, leftRe, rightRe) {
  const map = new Map();
  // Scope co-reference to a single sentence or line, not the whole paragraph,
  // so "AR-001 implements FR-001. AR-002 implements FR-002." does not cross-link.
  for (const seg of String(text || '').split(/\n+|(?<=\.)\s+/)) {
    const ids = parseRefs(seg);
    const lefts = ids.filter(id => leftRe.test(id));
    const rights = ids.filter(id => rightRe.test(id));
    for (const l of lefts) {
      const s = map.get(l) || new Set();
      rights.forEach(r => { if (r !== l) s.add(r); });
      map.set(l, s);
    }
  }
  const out = new Map();
  for (const [k, s] of map) out.set(k, [...s].sort(refCompare));
  return out;
}

function buildMatrix({ prd = '', sdd = '', adrs = {} } = {}) {
  const prdRefs = parseRefs(prd);
  const sddSet = new Set(parseRefs(sdd));
  const adrSets = Object.entries(adrs).map(([k, txt]) => {
    const m = k.match(/ADR-\d+/);
    return [m ? m[0] : k, new Set(parseRefs(txt))];
  });
  const adrsFor = id => adrSets.filter(([, s]) => s.has(id)).map(([k]) => k).sort(refCompare);

  const uatVerifies = linksWithin(prd, /^UAT-/, REQ_RE);
  const arTrace = linksWithin(sdd, /^AR-/, REQ_RE);

  const uatsForReq = new Map();
  for (const [uat, reqs] of uatVerifies) {
    for (const r of reqs) {
      const set = uatsForReq.get(r) || new Set();
      set.add(uat);
      uatsForReq.set(r, set);
    }
  }

  const requirements = prdRefs.filter(id => REQ_RE.test(id)).map(id => ({
    id,
    family: id.split('-')[0],
    inSdd: sddSet.has(id),
    sections: sectionAnchors(sdd, id),
    adrs: adrsFor(id),
    uats: [...(uatsForReq.get(id) || [])].sort(refCompare),
    coverage: sddSet.has(id) ? 'covered' : 'orphan',
  }));

  const uats = prdRefs.filter(id => /^UAT-/.test(id)).map(id => ({
    id, verifies: uatVerifies.get(id) || [],
  }));

  const ars = parseRefs(sdd).filter(id => /^AR-/.test(id)).map(id => ({
    id, tracesTo: arTrace.get(id) || [], adrs: adrsFor(id),
  }));

  const orphans = requirements.filter(r => r.coverage === 'orphan').map(r => r.id);
  return { requirements, ars, uats, orphans };
}

function fmtSections(secs) {
  return secs.length ? secs.map(s => `[${s.section}](#${s.slug})`).join(', ') : '—';
}

function renderCoverageBlock(matrix) {
  const { requirements, ars, uats, orphans } = matrix;
  let out = `> ${orphans.length} orphan(s): genuine coverage gaps — a requirement defined in the PRD with no matching mention in the SDD. Notation-only artifacts are already resolved by symmetric ID expansion.\n\n`;
  if (orphans.length) out += `**Orphans:** ${orphans.join(', ')}\n\n`;
  out += '| Requirement | In SDD | SDD Sections | Related ADRs | UAT | Coverage |\n';
  out += '| --- | --- | --- | --- | --- | --- |\n';
  out += requirements.map(r =>
    `| ${r.id} | ${r.inSdd ? 'yes' : 'no'} | ${fmtSections(r.sections)} | ${r.adrs.join(', ') || '—'} | ${r.uats.join(', ') || '—'} | ${r.coverage === 'covered' ? '✅ Covered' : '⚠️ Orphan'} |`
  ).join('\n') + '\n';
  if (ars.length) {
    out += '\n**Architectural Requirements**\n\n| AR | Traces to | In ADRs |\n| --- | --- | --- |\n';
    out += ars.map(a => `| ${a.id} | ${a.tracesTo.join(', ') || '—'} | ${a.adrs.join(', ') || '—'} |`).join('\n') + '\n';
  }
  if (uats.length) {
    out += '\n**Acceptance Tests**\n\n| UAT | Verifies |\n| --- | --- |\n';
    out += uats.map(u => `| ${u.id} | ${u.verifies.join(', ') || '—'} |`).join('\n') + '\n';
  }
  return out;
}

function renderMarkdown(matrix) {
  return `# Traceability Matrix\n\n${renderCoverageBlock(matrix)}`;
}

function esc(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function renderHtml(matrix) {
  const trs = matrix.requirements.map(r =>
    `<tr><td>${esc(r.id)}</td><td class="${r.inSdd ? 'ok' : 'gap'}">${r.inSdd ? 'yes' : 'no'}</td><td>${esc(r.adrs.join(', ') || '—')}</td><td>${esc(r.uats.join(', ') || '—')}</td><td>${r.coverage === 'covered' ? '✅' : '⚠️'}</td></tr>`
  ).join('');
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Traceability Matrix</title>
<style>body{font-family:system-ui,sans-serif;margin:2rem}table{border-collapse:collapse}td,th{border:1px solid #ccc;padding:.4rem .6rem}.gap{color:#b00;font-weight:bold}.ok{color:#070}</style>
</head><body><h1>Traceability Matrix</h1>
<table><thead><tr><th>Requirement</th><th>In SDD</th><th>Related ADRs</th><th>UAT</th><th>Coverage</th></tr></thead>
<tbody>${trs}</tbody></table></body></html>`;
}

function injectCoverage(sdd, block) {
  const wrapped = `${START}\n\n${block}\n${END}`;
  const s = String(sdd || '');
  const si = s.indexOf(START), ei = s.indexOf(END);
  if (si !== -1 && ei !== -1 && ei > si) {
    return s.slice(0, si) + wrapped + s.slice(ei + END.length);
  }
  const sep = s.endsWith('\n') ? '' : '\n';
  return s + `${sep}\n## 16. Requirement Coverage Index\n\n${wrapped}\n`;
}

function loadProduct(dir) {
  const read = p => fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : '';
  const adrDir = path.join(dir, 'adr');
  const adrs = {};
  if (fs.existsSync(adrDir)) {
    for (const f of fs.readdirSync(adrDir)) {
      if (f.endsWith('.md')) {
        const m = f.match(/ADR-\d+/);
        adrs[m ? m[0] : f] = read(path.join(adrDir, f));
      }
    }
  }
  return { prd: read(path.join(dir, 'prd', 'prd.md')), sdd: read(path.join(dir, 'sdd', 'sdd.md')), adrs };
}

module.exports = {
  parseRefs, expandRange, sectionAnchors, buildMatrix,
  renderMarkdown, renderHtml, renderCoverageBlock, injectCoverage, loadProduct,
};

if (require.main === module) {
  const dir = process.argv[2] || '.product';
  const matrix = buildMatrix(loadProduct(dir));
  fs.writeFileSync(path.join(dir, 'traceability.md'), renderMarkdown(matrix));
  fs.writeFileSync(path.join(dir, 'traceability.html'), renderHtml(matrix));
  const sddPath = path.join(dir, 'sdd', 'sdd.md');
  if (fs.existsSync(sddPath)) {
    fs.writeFileSync(sddPath, injectCoverage(fs.readFileSync(sddPath, 'utf8'), renderCoverageBlock(matrix)));
  } else {
    console.warn(`traceability: ${sddPath} not found; skipped coverage-index injection.`);
  }
  console.log(`Wrote traceability for ${matrix.requirements.length} requirements (${matrix.orphans.length} orphan(s)).`);
}
